FROM golang:1.17.0-alpine

RUN apk update && apk add git

WORKDIR /go/src/github.com/Doer-org/hack-camp_vol4_2022
COPY . .

# RUN go get github.com/cosmtrek/air
# RUN go build main.go

# RUN chmod -R 755 /go/src/app
